module.exports = {
  EmailExists: 'Email já cadsatrado.',
  UserSuccessLogin: 'Usuário logado com sucesso.',
  IncorrectLogin: 'Credenciais incorretas.',
  UserLogout: 'Usuário deslogado com sucesso.',
  UserNotAuthorized: 'Usuário não autorizado.',
  VerificationCodeHasSent: 'Código de verificação enviado.',
  EmailVerifiedSuccess: 'Email verificado com sucesso.',
  EmailFailedVerify: 'Falha ao verificar o e-mail.',
  EmailAlreadyVerified: 'O email já foi verificado.',
  VerificationTokenWrong: 'Código de verificação incorreto.',
  VerificationTokenIsExpired: 'Código de verificação expirado.',

  DataSuccessCreate: 'Criado com sucesso.',
  DataFailedCreate: 'Falha ao criar.',
  DataFound: 'Dados encontrados.',
  DataNotFound: 'Dados não encontrados.',
  DataSuccessUpdate: 'Dados atualizados.',
  DataFailedUpdate: 'Dados não atualizados',
  DataSuccessDelete: 'Dados deletados',
  DataFailedDelete: 'Falha ao deletar dados.',
  DataSuccessRestored: 'Dados restaurados.',
  DataFailedRestored: 'Falha ao restaurar dados.',
  FieldError: 'Entrada inválida.',
  MissingFields: 'Preencha todos dos campos',
  StatusError: 'Falha interna do servidor.',
  NotFoundMsg: 'Não encontrado.',
};
