module.exports = {
  UserExists: 'username already exists',
  UserSuccessLogin: 'user logged in successfully',
  IncorrectLogin: 'wrong user credentials',
  UserLogout: 'user logged out',
  UserNotAuthorized: 'this user is not authorized',
  VerificationCodeHasSent: 'verification code has been sent',
  EmailVerifiedSuccess: 'email successfully verified',
  EmailFailedVerify: 'email not verify',
  EmailAlreadyVerified: 'email already verified',
  VerificationTokenWrong: 'wrong verification code',
  VerificationTokenIsExpired: 'verification code expired',
  EmailAlreadyExists: 'email already exists',
  UserNameAlreadyExists: 'username already exists',

  DataSuccessCreate: 'data created',
  DataFailedCreate: 'data not created',
  DataFound: 'data found',
  DataNotFound: 'data not found',
  NotFoundMsg: 'not found',
  DataSuccessUpdate: 'data updated',
  DataFailedUpdate: 'data not updated',
  DataSuccessDelete: 'data deleted',
  DataFailedDelete: 'data not deleted',
  DataSuccessRestored: 'data restored',
  DataFailedRestored: 'data not restored',
  FieldError: 'invalid input',
  MissingFields: 'fill in all fields',
  DataAlreadyExists: 'this name already exists',
  StatusError: 'something went wrong',
};
